-- Database setup simplified to only provide the `test` table as requested

-- Enable necessary extensions
-- Create only the required `test` table
CREATE TABLE IF NOT EXISTS public.test (
  ao VARCHAR(2000) NOT NULL,
  channel VARCHAR(1000) NULL,
  date_created TIMESTAMP NULL,
  workorder VARCHAR(2000) NOT NULL,
  odp VARCHAR(2000) NULL,
  service_no VARCHAR(2000) NULL,
  description TEXT NULL,
  address TEXT NULL,
  customer_name VARCHAR(2000) NULL,
  workzone VARCHAR(1000) NULL,
  status_date TIMESTAMP NULL,
  contact_phone VARCHAR(200) NULL,
  booking_date TIMESTAMP NULL,
  hsa VARCHAR(2000) NULL,
  branch VARCHAR(1000) NULL,
  cluster VARCHAR(1000) NULL,
  mitra VARCHAR(1000) NULL,
  labor_teknisi VARCHAR(1000) NULL,
  kategori VARCHAR(1000) NULL,
  update_lapangan TEXT NULL,
  symptom TEXT NULL,
  engineering_memo TEXT NULL,
  tikor_inputan_pelanggan VARCHAR(2000) NULL,
  tikor_real_pelanggan VARCHAR(2000) NULL,
  selisih TEXT NULL,
  umur_manja VARCHAR(1000) NULL,
  kategori_manja VARCHAR(1000) NULL,
  sheet_aktivasi VARCHAR(1000) NULL,
  tanggal_ps DATE NULL,
  tinjut_hd_oplang TEXT NULL,
  keterangan_hd_oplang TEXT NULL,
  suberrorcode VARCHAR(1000) NULL,
  uic VARCHAR(1000) NULL,
  update_uic VARCHAR(1000) NULL,
  keterangan_uic TEXT NULL,
  status_bima VARCHAR(1000) NULL,
  status_dsc VARCHAR(1000) NULL,
  sisa_manja NUMERIC(10, 2) NULL,
  bulan_order VARCHAR(200) NULL,
  bulan_ps VARCHAR(200) NULL,
  backup VARCHAR(1000) NULL,
  lat_inputan NUMERIC(10, 6) NULL,
  long_inputan NUMERIC(10, 6) NULL,
  lat_real TEXT NULL,
  long_real TEXT NULL,
  username VARCHAR(2000) NULL,
  sending_status VARCHAR(1000) NULL,
  timestamp DATE NULL,
  sc_order_no TEXT NULL,
  service_area TEXT NULL,
  status_kpro TEXT NULL,
  CONSTRAINT test_pkey1 PRIMARY KEY (ao)
);
